blank_issues_enabled: false
contact_links:
  - name: Questions about the Lean community
    url: https://leanprover.zulipchat.com
    about: This repository is only for registering project intentions. For questions, come to the Lean Zulip.
